### ISSUE TITLE
A minor deficiency of Description in README.

### ISSUE THREAD

**Issue by l-s0r-l** [CAU-OSS-2019/team-project-team1#16]
Hi. I've been interested in your project.

I discovered a little[trivial] lack in your README,
with respect to Program Execution & Develolp Environment and (e.g operating system).

On Linux, 
can't execute this program.

Only on Windows,
can execute this program.

**Comment by kawoou** [comment]
In Linux or MacOS environment, Can to build.

```bash
make all
cd bin/
```
