### ISSUE TITLE
컴파일 시 KISA_SHA256 api 관련 에러

### ISSUE THREAD

**Issue by l-s0r-l** [CAU-OSS-2019/team-project-team1#18]
KISA_SHA256.h 파일의 KISA_SHA256 api 관련 에러 발생으로 인해 소스의 컴파일이 되지 않습니다.

**Comment by rmfpdlxmtidl** [comment]
저는 컴파일 시 에러가 발생하지 않았는데 혹시 어떤 환경인가요?

제 환경은 Windows 10 64bit, Visual Studio 2017, Release 모드 입니다.

**Comment by rmfpdlxmtidl** [comment]
KISA_SHA256.h를 수정하지 않고 빌드 시에 Pre-define으로 USER_LITTLE_ENDIAN 지정하면 됩니다
