### ISSUE TITLE
input 관련 issue

### ISSUE THREAD

**Issue by nh7881** [CAU-OSS-2019/team-project-team1#5]
안녕하세요.
issue는 아래와 같습니다.

input error
프로그램을 실행 후 비밀번호를 만든 후 메인 화면에서 1(buy)를 선택한 후 5이상의 숫자를 입력시 error가 발생하는 것을 볼 수 있었습니다. 편의를 위해 해당 부분 예외 처리가 있으면 좋을것 같습니다. 조만간 해당 부분 직접 수정하여 pull request 드리도록 하겠습니다.
![image](https://user-images.githubusercontent.com/24385575/59550562-0a804680-8fa7-11e9-9ac3-33c189905f3c.png)

**Comment by rmfpdlxmtidl** [comment]
지금 현 상태에선 input 예외처리가 중요한 것이 아닙니다. Input 예외처리를 해도 앞으로 개발하는 과정에서 input은 얼마든지 형식이나 내용이 바뀔 수 있기 때문에  지금 개발 상황에서 invalid한 input을 가려내는 것은 무의미합니다. 더구나 임시적으로 UI를 c++로 만들어서 이런 문제가 발생하는 거고, UI는 Java나 Swift로 개발할 예정이기 때문에 이 문제는 개인적으로 임시적으로 발생한 문제라고 생각합니다. 그것보다 프로그램의 논리적인 측면에서 문제가 있는지 봐주시면 감사하겠습니다:)
